import 'package:flutter/material.dart';
import '../../l10n/app_localizations.dart';

String getLocalizedCategory(BuildContext context, String categoryName) {
  final l10n = AppLocalizations.of(context);
  if (l10n == null) return categoryName;
  final code = l10n.localeName; // 'en', 'hi', 'es', etc.

  const translations = <String, Map<String, String>>{
    'Food & Dining': {
      'en': 'Food & Dining',
      'hi': 'भोजन और खान-पान',
      'es': 'Comida y Restaurantes',
      'fr': 'Restauration',
      'de': 'Essen & Trinken',
      'ja': '外食・フード',
      'zh': '餐饮美食',
      'pt': 'Comida e Jantar',
      'ru': 'Еда и рестораны',
      'ko': '식비 및 외식',
      'ar': 'الطعام والمطاعم',
      'it': 'Cibo e Ristorazione',
    },
    'Shopping': {
      'en': 'Shopping',
      'hi': 'खरीदारी',
      'es': 'Compras',
      'fr': 'Shopping',
      'de': 'Shopping',
      'ja': 'ショッピング',
      'zh': '购物',
      'pt': 'Compras',
      'ru': 'Покупки',
      'ko': '쇼핑',
      'ar': 'التسوق',
      'it': 'Shopping',
    },
    'Transport': {
      'en': 'Transport',
      'hi': 'परिवहन',
      'es': 'Transporte',
      'fr': 'Transport',
      'de': 'Transport',
      'ja': '交通費',
      'zh': '交通出行',
      'pt': 'Transporte',
      'ru': 'Транспорт',
      'ko': '교통',
      'ar': 'المواصلات',
      'it': 'Trasporti',
    },
    'Entertainment': {
      'en': 'Entertainment',
      'hi': 'मनोरंजन',
      'es': 'Entretenimiento',
      'fr': 'Divertissement',
      'de': 'Unterhaltung',
      'ja': 'エンターテイメント',
      'zh': '娱乐消遣',
      'pt': 'Entretenimento',
      'ru': 'Развлечения',
      'ko': '문화 및 여가',
      'ar': 'الترفيه',
      'it': 'Intrattenimento',
    },
    'Health': {
      'en': 'Health',
      'hi': 'स्वास्थ्य',
      'es': 'Salud',
      'fr': 'Santé',
      'de': 'Gesundheit',
      'ja': '健康・医療',
      'zh': '医疗健康',
      'pt': 'Saúde',
      'ru': 'Здоровье',
      'ko': '건강 및 의료',
      'ar': 'الصحة',
      'it': 'Salute',
    },
    'Bills': {
      'en': 'Bills',
      'hi': 'बिल',
      'es': 'Facturas',
      'fr': 'Factures',
      'de': 'Rechnungen',
      'ja': '請求書・支払',
      'zh': '账单缴费',
      'pt': 'Contas',
      'ru': 'Счета',
      'ko': '공과금',
      'ar': 'الفواتير',
      'it': 'Bollette',
    },
    'Education': {
      'en': 'Education',
      'hi': 'शिक्षा',
      'es': 'Educación',
      'fr': 'Éducation',
      'de': 'Bildung',
      'ja': '教育・学習',
      'zh': '教育学习',
      'pt': 'Educação',
      'ru': 'Образование',
      'ko': '교육',
      'ar': 'التعليم',
      'it': 'Istruzione',
    },
    'Travel': {
      'en': 'Travel',
      'hi': 'यात्रा',
      'es': 'Viajes',
      'fr': 'Voyage',
      'de': 'Reisen',
      'ja': '旅行',
      'zh': '旅游出行',
      'pt': 'Viagem',
      'ru': 'Путешествия',
      'ko': '여행',
      'ar': 'السفر',
      'it': 'Viaggi',
    },
    'Groceries': {
      'en': 'Groceries',
      'hi': 'किराने का सामान',
      'es': 'Comestibles',
      'fr': 'Courses',
      'de': 'Lebensmittel',
      'ja': '食料品',
      'zh': '日常买菜',
      'pt': 'Supermercado',
      'ru': 'Продукты',
      'ko': '식료품',
      'ar': 'البقالة',
      'it': 'Spesa',
    },
    'Salary': {
      'en': 'Salary',
      'hi': 'वेतन',
      'es': 'Salario',
      'fr': 'Salaire',
      'de': 'Gehalt',
      'ja': '給与',
      'zh': '工资收入',
      'pt': 'Salário',
      'ru': 'Зарплата',
      'ko': '급여',
      'ar': 'الراتب',
      'it': 'Stipendio',
    },
    'Freelance': {
      'en': 'Freelance',
      'hi': 'फ्रीलांस',
      'es': 'Freelance',
      'fr': 'Freelance',
      'de': 'Freiberuflich',
      'ja': 'フリーランス',
      'zh': '兼职外包',
      'pt': 'Freelance',
      'ru': 'Фриланс',
      'ko': '프리랜서',
      'ar': 'العمل الحر',
      'it': 'Freelance',
    },
    'Investment': {
      'en': 'Investment',
      'hi': 'निवेश',
      'es': 'Inversión',
      'fr': 'Investissement',
      'de': 'Investition',
      'ja': '投資',
      'zh': '理财投资',
      'pt': 'Investimento',
      'ru': 'Инвестиции',
      'ko': '투자',
      'ar': 'الاستثمار',
      'it': 'Investimenti',
    },
    'Gift': {
      'en': 'Gift',
      'hi': 'उपहार',
      'es': 'Regalo',
      'fr': 'Cadeau',
      'de': 'Geschenk',
      'ja': 'ギフト',
      'zh': '人情礼金',
      'pt': 'Presente',
      'ru': 'Подарки',
      'ko': '선물',
      'ar': 'هدية',
      'it': 'Regali',
    },
    'Other': {
      'en': 'Other',
      'hi': 'अन्य',
      'es': 'Otros',
      'fr': 'Autre',
      'de': 'Sonstiges',
      'ja': 'その他',
      'zh': '其他',
      'pt': 'Outros',
      'ru': 'Другое',
      'ko': '기타',
      'ar': 'أخرى',
      'it': 'Altro',
    },
  };

  final categoryTranslations = translations[categoryName];
  if (categoryTranslations == null) return categoryName;
  return categoryTranslations[code] ?? categoryTranslations['en'] ?? categoryName;
}
