// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPzXbBL7fM46uMFdLA0juM3zE1Lj02tx0',
    appId: '1:969305779854:web:ff8373b4015fd4b735a3df',
    messagingSenderId: '969305779854',
    projectId: 'moneybuddy-372a5',
    authDomain: 'moneybuddy-372a5.firebaseapp.com',
    storageBucket: 'moneybuddy-372a5.firebasestorage.app',
    measurementId: 'G-7BPNKT6NHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnbhqczTxNy5XKLssm51NPA5NZKw5E7go',
    appId: '1:969305779854:android:07e0fa1125b7a69c35a3df',
    messagingSenderId: '969305779854',
    projectId: 'moneybuddy-372a5',
    storageBucket: 'moneybuddy-372a5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1uk9D0UQoU44KOpB0NBc4aWbhkqCM7Mc',
    appId: '1:969305779854:ios:44dc404d70238a5335a3df',
    messagingSenderId: '969305779854',
    projectId: 'moneybuddy-372a5',
    storageBucket: 'moneybuddy-372a5.firebasestorage.app',
    androidClientId: '969305779854-4co6pre0u1emtdc43aq9h7tug3ekh7ba.apps.googleusercontent.com',
    iosClientId: '969305779854-1u976i18mlacqcir4vs2b62ipo4m4cpj.apps.googleusercontent.com',
    iosBundleId: 'com.moneybuddy.moneyBuddy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1uk9D0UQoU44KOpB0NBc4aWbhkqCM7Mc',
    appId: '1:969305779854:ios:ffd575255367493f35a3df',
    messagingSenderId: '969305779854',
    projectId: 'moneybuddy-372a5',
    storageBucket: 'moneybuddy-372a5.firebasestorage.app',
    iosBundleId: 'moneybuddy-372a5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPzXbBL7fM46uMFdLA0juM3zE1Lj02tx0',
    appId: '1:969305779854:web:abda78e1acd0af4735a3df',
    messagingSenderId: '969305779854',
    projectId: 'moneybuddy-372a5',
    authDomain: 'moneybuddy-372a5.firebaseapp.com',
    storageBucket: 'moneybuddy-372a5.firebasestorage.app',
    measurementId: 'G-3ZBH8QYH5R',
  );
}
